# Generated by Django 5.2 on 2025-05-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_artiles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiles',
            name='category',
            field=models.CharField(choices=[('animals', 'Животные'), ('people', 'Люди'), ('food', 'Еда'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория'),
        ),
    ]
